// Package report generates a report from the state of a cluster
//
// Code generated by go generate; DO NOT EDIT.
//
// This file was generated by gen_list_converter.go at 2019-02-20 23:41:07.782928058 +0200 EET m=+0.000547610
package report

import (
	apps "k8s.io/api/apps/v1"
	core "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/types"
)

// servicesToServiceIds convert a list of Services to a list of their ids
func servicesToServiceIds(objects []core.Service) []types.UID {

	if objects == nil {
		return make([]types.UID, 0, 0)
	}

	ids := make([]types.UID, 0, len(objects))
	for _, provider := range objects {
		ids = append(ids, provider.UID)
	}

	return ids
}

// podsToPodIds convert a list of Pods to a list of their ids
func podsToPodIds(objects []core.Pod) []types.UID {

	if objects == nil {
		return make([]types.UID, 0, 0)
	}

	ids := make([]types.UID, 0, len(objects))
	for _, provider := range objects {
		ids = append(ids, provider.UID)
	}

	return ids
}

// deploymentsToDeploymentIds convert a list of Deployments to a list of their ids
func deploymentsToDeploymentIds(objects []apps.Deployment) []types.UID {

	if objects == nil {
		return make([]types.UID, 0, 0)
	}

	ids := make([]types.UID, 0, len(objects))
	for _, provider := range objects {
		ids = append(ids, provider.UID)
	}

	return ids
}
