// Package connector regroups all the basic CRUD functions to access the objects in the cluster
//
// Code generated by go generate; DO NOT EDIT.
//
// This file was generated by gen_connector_namespace_metrics.go at 2019-06-17 12:12:58.579992379 +0300 EEST m=+0.000831968
package connector

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metricsv1beta1 "k8s.io/metrics/pkg/apis/metrics/v1beta1"
	metrics "k8s.io/metrics/pkg/client/clientset/versioned"
)

// GetPodMetricses returns all the PodMetrics. If an empty namespace is given, returns all the PodMetrics
func GetPodMetricses(metrics *metrics.Clientset, namespace string) ([]metricsv1beta1.PodMetrics, error) {

	client := metrics.MetricsV1beta1().PodMetricses(namespace)
	podMetrics, err := client.List(metav1.ListOptions{})
	if err != nil {
		return []metricsv1beta1.PodMetrics{}, err
	}
	return podMetrics.Items, nil
}

// GetPodMetrics returns the PodMetrics by its name. An optional namespace can be given, if none is given
// the operation takes place in the default name space.
func GetPodMetrics(metrics *metrics.Clientset, namespace string, name string) (*metricsv1beta1.PodMetrics, error) {

	client := metrics.MetricsV1beta1().PodMetricses(getValidNameSpace(namespace))
	return client.Get(name, metav1.GetOptions{})
}
