// Package connector regroups all the basic CRUD functions to access the objects in the cluster
//
// Code generated by go generate; DO NOT EDIT.
//
// This file was generated by gen_connector_cluster_metrics.go at 2019-06-17 12:12:58.179171776 +0300 EEST m=+0.000806133
package connector

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metricsv1beta1 "k8s.io/metrics/pkg/apis/metrics/v1beta1"
	metrics "k8s.io/metrics/pkg/client/clientset/versioned"
)

// GetNodeMetricses returns all the NodeMetrics.
func GetNodeMetricses(metrics *metrics.Clientset) ([]metricsv1beta1.NodeMetrics, error) {

	client := metrics.MetricsV1beta1().NodeMetricses()
	nodeMetrics, err := client.List(metav1.ListOptions{})
	if err != nil {
		return []metricsv1beta1.NodeMetrics{}, err
	}
	return nodeMetrics.Items, nil
}

// GetNodeMetrics returns the NodeMetrics by its name.
func GetNodeMetrics(metrics *metrics.Clientset, name string) (*metricsv1beta1.NodeMetrics, error) {

	client := metrics.MetricsV1beta1().NodeMetricses()
	return client.Get(name, metav1.GetOptions{})
}
